/**
 * Catàleg de badges. Cada badge té: id, nom, descripció, condició, imatge, categoria, dificultat.
 * La condició s'avalua a badgeService.evaluateBadge.
 */
export const BADGE_CATEGORIES = {
  VOLUME: "volume",
  INTENSITY: "intensity",
  CONSISTENCY: "consistency",
  EXPLORATION: "exploration",
  CHALLENGE: "challenge",
  SOCIAL: "social",
  FUN: "fun",
  META: "meta",
};

const BASE = "/badges/";

export const BADGE_CATALOG = [
  // Volum de lectura
  {
    id: "primera-pagina",
    name: "Primera Pàgina",
    description: "Has llegit la primera pàgina registrada.",
    condition: "first_page",
    image: `${BASE}badge-primera-pagina.png`,
    category: BADGE_CATEGORIES.VOLUME,
    difficulty: 1,
  },
  {
    id: "primer-llibre",
    name: "Primer Llibre",
    description: "Has completat el teu primer llibre.",
    condition: "books_completed",
    conditionValue: 1,
    image: `${BASE}badge-primer-llibre.png`,
    category: BADGE_CATEGORIES.VOLUME,
    difficulty: 1,
  },
  {
    id: "biblioteca-en-creixement",
    name: "Biblioteca en Creixement",
    description: "10 llibres completats.",
    condition: "books_completed",
    conditionValue: 10,
    image: `${BASE}badge-biblioteca-en-creixement.png`,
    category: BADGE_CATEGORIES.VOLUME,
    difficulty: 2,
  },
  {
    id: "petita-biblioteca",
    name: "Petita Biblioteca",
    description: "50 llibres completats.",
    condition: "books_completed",
    conditionValue: 50,
    image: `${BASE}badge-petita-biblioteca.png`,
    category: BADGE_CATEGORIES.VOLUME,
    difficulty: 4,
  },
  {
    id: "biblioteca-infinita",
    name: "Biblioteca Infinita",
    description: "100 llibres completats.",
    condition: "books_completed",
    conditionValue: 100,
    image: `${BASE}badge-biblioteca-infinita.png`,
    category: BADGE_CATEGORIES.VOLUME,
    difficulty: 5,
  },
  {
    id: "1000-pagines",
    name: "1000 Pàgines",
    description: "Has llegit 1000 pàgines.",
    condition: "total_pages",
    conditionValue: 1000,
    image: `${BASE}badge-1000-pagines.png`,
    category: BADGE_CATEGORIES.VOLUME,
    difficulty: 1,
  },
  {
    id: "5000-pagines",
    name: "5000 Pàgines",
    description: "Has llegit 5000 pàgines.",
    condition: "total_pages",
    conditionValue: 5000,
    image: `${BASE}badge-5000-pagines.png`,
    category: BADGE_CATEGORIES.VOLUME,
    difficulty: 2,
  },
  {
    id: "10000-pagines",
    name: "10.000 Pàgines",
    description: "Has llegit 10.000 pàgines.",
    condition: "total_pages",
    conditionValue: 10000,
    image: `${BASE}badge-10000-pagines.png`,
    category: BADGE_CATEGORIES.VOLUME,
    difficulty: 4,
  },
  {
    id: "50000-pagines",
    name: "50.000 Pàgines",
    description: "Has llegit 50.000 pàgines.",
    condition: "total_pages",
    conditionValue: 50000,
    image: `${BASE}badge-50000-pagines.png`,
    category: BADGE_CATEGORIES.VOLUME,
    difficulty: 5,
  },
  // Intensitat
  {
    id: "sprint-lector",
    name: "Sprint Lector",
    description: "100 pàgines en un sol dia.",
    condition: "pages_in_day",
    conditionValue: 100,
    image: `${BASE}badge-sprint-lector.png`,
    category: BADGE_CATEGORIES.INTENSITY,
    difficulty: 2,
  },
  {
    id: "hipervelocitat",
    name: "Hipervelocitat",
    description: "200 pàgines en un sol dia.",
    condition: "pages_in_day",
    conditionValue: 200,
    image: `${BASE}badge-hipervelocitat.png`,
    category: BADGE_CATEGORIES.INTENSITY,
    difficulty: 4,
  },
  {
    id: "cap-de-setamana-literari",
    name: "Cap de Setmana Literari",
    description: "300 pàgines en un cap de setmana.",
    condition: "pages_in_weekend",
    conditionValue: 300,
    image: `${BASE}badge-cap-de-setamana-literari.png`,
    category: BADGE_CATEGORIES.INTENSITY,
    difficulty: 3,
  },
  {
    id: "lector-nocturn",
    name: "Lector Nocturn",
    description: "Has llegit després de mitjanit.",
    condition: "read_after_midnight",
    image: `${BASE}badge-lector-nocturn.png`,
    category: BADGE_CATEGORIES.INTENSITY,
    difficulty: 2,
  },
  // Constància
  {
    id: "habit-lector",
    name: "Hàbit Lector",
    description: "7 dies seguits amb lectura registrada.",
    condition: "streak_days",
    conditionValue: 7,
    image: `${BASE}badge-habit-lector.png`,
    category: BADGE_CATEGORIES.CONSISTENCY,
    difficulty: 2,
  },
  {
    id: "ratxa-de-lectura",
    name: "Ratxa de Lectura",
    description: "30 dies seguits amb lectura registrada.",
    condition: "streak_days",
    conditionValue: 30,
    image: `${BASE}badge-ratxa-de-lectura.png`,
    category: BADGE_CATEGORIES.CONSISTENCY,
    difficulty: 4,
  },
  {
    id: "disciplina-literaria",
    name: "Disciplina Literària",
    description: "100 dies seguits amb lectura registrada.",
    condition: "streak_days",
    conditionValue: 100,
    image: `${BASE}badge-disciplina-literaria.png`,
    category: BADGE_CATEGORIES.CONSISTENCY,
    difficulty: 5,
  },
  {
    id: "un-any-llegint",
    name: "Un Any Llegint",
    description: "365 dies amb almenys lectura registrada.",
    condition: "total_activity_days",
    conditionValue: 365,
    image: `${BASE}badge-un-any-llegint.png`,
    category: BADGE_CATEGORIES.CONSISTENCY,
    difficulty: 5,
  },
  // Exploració
  {
    id: "explorador-de-generes",
    name: "Explorador de Gèneres",
    description: "5 gèneres diferents de llibres completats.",
    condition: "genres_count",
    conditionValue: 5,
    image: `${BASE}badge-explorador-de-generes.png`,
    category: BADGE_CATEGORIES.EXPLORATION,
    difficulty: 2,
  },
  {
    id: "polifacetic",
    name: "Polifacètic",
    description: "10 gèneres diferents de llibres completats.",
    condition: "genres_count",
    conditionValue: 10,
    image: `${BASE}badge-polifacetic.png`,
    category: BADGE_CATEGORIES.EXPLORATION,
    difficulty: 4,
  },
  // Reptes
  {
    id: "classic-conquerit",
    name: "Clàssic Conquerit",
    description: "Has completat un llibre clàssic.",
    condition: "classics_completed",
    conditionValue: 1,
    image: `${BASE}badge-classic-conquerit.png`,
    category: BADGE_CATEGORIES.CHALLENGE,
    difficulty: 2,
  },
  {
    id: "classic-rere-classic",
    name: "Clàssic Rere Clàssic",
    description: "5 llibres clàssics completats.",
    condition: "classics_completed",
    conditionValue: 5,
    image: `${BASE}badge-classic-rere-classic.png`,
    category: BADGE_CATEGORIES.CHALLENGE,
    difficulty: 4,
  },
  {
    id: "gran-novela",
    name: "Gran Novel·la",
    description: "Llibre de més de 500 pàgines completat.",
    condition: "book_pages_min",
    conditionValue: 500,
    image: `${BASE}badge-gran-novela.png`,
    category: BADGE_CATEGORIES.CHALLENGE,
    difficulty: 3,
  },
  {
    id: "monolit-literari",
    name: "Monòlit Literari",
    description: "Llibre de més de 1000 pàgines completat.",
    condition: "book_pages_min",
    conditionValue: 1000,
    image: `${BASE}badge-monolit-literari.png`,
    category: BADGE_CATEGORIES.CHALLENGE,
    difficulty: 5,
  },
  // Socials
  {
    id: "primera-ressenya",
    name: "Primera Ressenya",
    description: "Has escrit la teva primera ressenya.",
    condition: "reviews_count",
    conditionValue: 1,
    image: `${BASE}badge-primera-ressenya.png`,
    category: BADGE_CATEGORIES.SOCIAL,
    difficulty: 1,
  },
  {
    id: "critic-literari",
    name: "Crític Literari",
    description: "10 ressenyes publicades.",
    condition: "reviews_count",
    conditionValue: 10,
    image: `${BASE}badge-critic-literari.png`,
    category: BADGE_CATEGORIES.SOCIAL,
    difficulty: 4,
  },
  {
    id: "ressenya-estimada",
    name: "Ressenya Estimada",
    description: "Una ressenya teva amb 10 o més likes.",
    condition: "review_with_10_likes",
    image: `${BASE}badge-ressenya-estimada.png`,
    category: BADGE_CATEGORIES.SOCIAL,
    difficulty: 4,
  },
  {
    id: "company-de-comunitat",
    name: "Company de Comunitat",
    description: "Has encoratjat 10 vegades.",
    condition: "encouragements_sent",
    conditionValue: 10,
    image: `${BASE}badge-company-de-comunitat.png`,
    category: BADGE_CATEGORIES.SOCIAL,
    difficulty: 2,
  },
  {
    id: "motivador-de-comunitat",
    name: "Motivador de Comunitat",
    description: "Has encoratjat 50 vegades.",
    condition: "encouragements_sent",
    conditionValue: 50,
    image: `${BASE}badge-motivador-de-comunitat.png`,
    category: BADGE_CATEGORIES.SOCIAL,
    difficulty: 5,
  },
  // Curiosos
  {
    id: "cafe-i-llibre",
    name: "Cafè i Llibre",
    description: "5 dies seguits llegint al matí.",
    condition: "morning_streak",
    conditionValue: 5,
    image: `${BASE}badge-cafe-i-llibre.png`,
    category: BADGE_CATEGORIES.FUN,
    difficulty: 3,
  },
  {
    id: "insomni-lector",
    name: "Insomni Lector",
    description: "3 nits seguides llegint després de mitjanit.",
    condition: "night_streak",
    conditionValue: 3,
    image: `${BASE}badge-insomni-lector.png`,
    category: BADGE_CATEGORIES.FUN,
    difficulty: 3,
  },
  {
    id: "devora-llibres",
    name: "Devora-Llibres",
    description: "3 llibres completats en un mes.",
    condition: "books_in_month",
    conditionValue: 3,
    image: `${BASE}badge-devora-llibres.png`,
    category: BADGE_CATEGORIES.FUN,
    difficulty: 3,
  },
  {
    id: "lectura-d-hivern",
    name: "Lectura d'Hivern",
    description: "Acabar un llibre al desembre.",
    condition: "book_completed_in_month",
    conditionValue: 12,
    image: `${BASE}badge-lectura-d-hivern.png`,
    category: BADGE_CATEGORIES.FUN,
    difficulty: 2,
  },
  {
    id: "lectura-d-estiu",
    name: "Lectura d'Estiu",
    description: "Acabar un llibre al juliol o agost.",
    condition: "book_completed_in_summer",
    image: `${BASE}badge-lectura-d-estiu.png`,
    category: BADGE_CATEGORIES.FUN,
    difficulty: 2,
  },
  // Meta
  {
    id: "arquitecte-de-biblioteca",
    name: "Arquitecte de Biblioteca",
    description: "100 llibres, 10.000 pàgines i 10 gèneres diferents.",
    condition: "architect",
    image: `${BASE}badge-arquitecte-de-biblioteca.png`,
    category: BADGE_CATEGORIES.META,
    difficulty: 5,
  },
];

/** Ordre de categories per a la visualització */
export const CATEGORY_ORDER = [
  BADGE_CATEGORIES.VOLUME,
  BADGE_CATEGORIES.INTENSITY,
  BADGE_CATEGORIES.CONSISTENCY,
  BADGE_CATEGORIES.EXPLORATION,
  BADGE_CATEGORIES.CHALLENGE,
  BADGE_CATEGORIES.SOCIAL,
  BADGE_CATEGORIES.FUN,
  BADGE_CATEGORIES.META,
];
